### ISSUE TITLE
Improve the devices list UI to be more useful and helpful

### ISSUE THREAD

**Issue by levibostian** [levibostian/BatteryBird#56]
# Tasks 

- [x] Try changing to a grid view instead of list. 
- [ ] For each cell, show the following info: 
	- [x] device name
	- [x] percentage battery remaining
	- [ ] if the device is connected or not
	- [ ] If a device is connected but we are unable to get the battery level, the UI for the battery level should indicate that perhaps this device does not allow you to check the battery level. 
	- [x]  If the device has never been connected, the UI for the battery level should indicate that you should connect device to get the first battery level update. 
- [x] On the screen, indicate when the app last checked levels of devices
